from elasticsearch import Elasticsearch, helpers
import csv


def getQueryToCloud():
  # Password for the 'elastic' user generated by Elasticsearch
  ELASTIC_PASSWORD = ""
  # Found in the 'Manage Deployment' page
  CLOUD_ID = ""
  # Create the client instance
  client = Elasticsearch(
    cloud_id=CLOUD_ID,
    basic_auth=("elastic", ELASTIC_PASSWORD)
  )
  # Successful response!
  info = client.info()
  print(info)
  
  idx_name = "connection_test"
  
  ret = client.search(index= idx_name, query={
      "bool": {
      "filter": [
        {"range": {
          "접수마감일": {
            "gte": "2023-09-02"
          }
        }
        }
      ]
    }
  })
  
  #print(ret)
  return ret

getQueryToCloud()